### ISSUE TITLE
Easy guest checkout

### ISSUE THREAD

**Issue by xopr** [ACKspace/ACKbar#14]
As an ACKbar guest, I would like to checkout with as few as possible steps.
So I can enjoy my beverage/purchase more quickly.

---
Deliverables;
* allow guest to `accept` checkout with negative balance
* give guest more time to read what amount should be deposited in the cash register to restore balance

Note that it still is possible to use `cash` to calculate change for a given money bill.

**Comment by Prodigity** [comment]
Fixed with PR #15
