### ISSUE TITLE
number rounding/float/parse error on cash audit `tool_kastelling.py`

### ISSUE THREAD

**Issue by xopr** [ACKspace/ACKbar#9]
When entering fractional numbers in `tool_kastelling.py` the numbers will deviate strongly:

### Steps to reproduce
* preferably, have an empty database
* start `python3 ./tool_kastelling.py` (verify that it says `..(minstens) 0.00 in de kas..`
* enter `5.1`

### Expected result
* It should say: `Er ligt 5.10 te veel in de kas!`
 
### Current result
* It says: `Er ligt 5.09 te veel in de kas!`

**Comment by Prodigity** [comment]
Good find.
I think reusing input_deposit() from console.py here would fix that problem, I'll look into it.

**Comment by xopr** [comment]
I was in a programming spree and managed to include a fix for this as well.
